version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Seoul
    open-pull-requests-limit: 5
    groups:
      development-dependencies:
        dependency-type: development
      production-dependencies:
        dependency-type: production
    labels: ["dependencies", "status: needs-review"]
    commit-message:
      prefix: "chore(deps)"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Seoul
    labels: ["dependencies", "area: ci", "status: needs-review"]
    commit-message:
      prefix: "ci(deps)"
